import { pgTable, text, varchar, real, integer, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
export const authConfig = pgTable("auth_config", {
    id: integer("id").primaryKey().default(1),
    accessCode: text("access_code").notNull(),
});
export const coletaGrupo1 = pgTable("coleta_grupo1", {
    id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
    createdAt: timestamp("created_at").defaultNow(),
    dataColeta: varchar("data_coleta", { length: 255 }).notNull(),
    linhaProducao: varchar("linha_producao", { length: 255 }).notNull(),
    sku: varchar("sku", { length: 255 }).notNull().default(''),
    pesoSacolaVarpe: real("peso_sacola_varpe").notNull().default(0),
    parametroPainel: real("parametro_painel").default(0),
    acrisson: real("acrisson").default(0),
    velocidadeLinha: real("velocidade_linha").notNull(),
    coreAttach: real("core_attach").notNull(),
    coreWrap: real("core_wrap").notNull(),
    surge: real("surge").notNull(),
    cuffEnd: real("cuff_end").notNull(),
    bead: real("bead").notNull(),
    legElastic: real("leg_elastic").notNull(),
    cuffElastic: real("cuff_elastic").notNull(),
    temporary: real("temporary").notNull(),
    topsheet: real("topsheet").notNull(),
    backsheet: real("backsheet").notNull(),
    frontal: real("frontal").notNull(),
    earAttach: real("ear_attach").notNull(),
    pulpFix: real("pulp_fix").notNull(),
    central: real("central").notNull(),
    release: real("release").notNull(),
    tapeOnBag: real("tape_on_bag").notNull(),
    filme1x1: real("filme_1x1").notNull(),
});
export const coletaGrupo2 = pgTable("coleta_grupo2", {
    id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
    createdAt: timestamp("created_at").defaultNow(),
    dataColeta: varchar("data_coleta", { length: 255 }).notNull(),
    linhaProducao: varchar("linha_producao", { length: 255 }).notNull(),
    sku: varchar("sku", { length: 255 }).notNull().default(''),
    pesoSacolaVarpe: real("peso_sacola_varpe").notNull().default(0),
    parametroPainel: real("parametro_painel").default(0),
    acrisson: real("acrisson").default(0),
    velocidadeLinha: real("velocidade_linha").notNull(),
    waistPacker: real("waist_packer").notNull(),
    isgElastic: real("isg_elastic").notNull(),
    waistElastic: real("waist_elastic").notNull(),
    isgSideSeal: real("isg_side_seal").notNull(),
    absorventFix: real("absorvent_fix").notNull(),
    outerEdge: real("outer_edge").notNull(),
    inner: real("inner").notNull(),
    bead: real("bead").notNull(),
    standingGather: real("standing_gather").notNull(),
    backflimFix: real("backflim_fix").notNull(),
    osgSideSeal: real("osg_side_seal").notNull(),
    osgElastico: real("osg_elastico").notNull(),
    nwSealContLateral: real("nw_seal_cont_lateral").notNull(),
    nwSealIntCentRal: real("nw_seal_int_cent_ral").notNull(),
    outSideBackFlm: real("out_side_back_flm").notNull(),
    topsheetFix: real("topsheet_fix").notNull(),
    coreWrap: real("core_wrap").notNull(),
    coreWrapSeal: real("core_wrap_seal").notNull(),
    matFix: real("mat_fix").notNull(),
});
export const insertColetaGrupo1Schema = createInsertSchema(coletaGrupo1).pick({
    dataColeta: true,
    linhaProducao: true,
    sku: true,
    pesoSacolaVarpe: true,
    parametroPainel: true,
    acrisson: true,
    velocidadeLinha: true,
    coreAttach: true,
    coreWrap: true,
    surge: true,
    cuffEnd: true,
    bead: true,
    legElastic: true,
    cuffElastic: true,
    temporary: true,
    topsheet: true,
    backsheet: true,
    frontal: true,
    earAttach: true,
    pulpFix: true,
    central: true,
    release: true,
    tapeOnBag: true,
    filme1x1: true,
});
export const insertColetaGrupo2Schema = createInsertSchema(coletaGrupo2).pick({
    dataColeta: true,
    linhaProducao: true,
    sku: true,
    pesoSacolaVarpe: true,
    parametroPainel: true,
    acrisson: true,
    velocidadeLinha: true,
    waistPacker: true,
    isgElastic: true,
    waistElastic: true,
    isgSideSeal: true,
    absorventFix: true,
    outerEdge: true,
    inner: true,
    bead: true,
    standingGather: true,
    backflimFix: true,
    osgSideSeal: true,
    osgElastico: true,
    nwSealContLateral: true,
    nwSealIntCentRal: true,
    outSideBackFlm: true,
    topsheetFix: true,
    coreWrap: true,
    coreWrapSeal: true,
    matFix: true,
});
export const insertAuthConfigSchema = createInsertSchema(authConfig).pick({
    accessCode: true,
});
