import { z } from "zod";
export declare const authConfig: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "auth_config";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "auth_config";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        accessCode: import("drizzle-orm/pg-core").PgColumn<{
            name: "access_code";
            tableName: "auth_config";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const coletaGrupo1: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "coleta_grupo1";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: "always";
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "coleta_grupo1";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        dataColeta: import("drizzle-orm/pg-core").PgColumn<{
            name: "data_coleta";
            tableName: "coleta_grupo1";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        linhaProducao: import("drizzle-orm/pg-core").PgColumn<{
            name: "linha_producao";
            tableName: "coleta_grupo1";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        sku: import("drizzle-orm/pg-core").PgColumn<{
            name: "sku";
            tableName: "coleta_grupo1";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        pesoSacolaVarpe: import("drizzle-orm/pg-core").PgColumn<{
            name: "peso_sacola_varpe";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        parametroPainel: import("drizzle-orm/pg-core").PgColumn<{
            name: "parametro_painel";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        acrisson: import("drizzle-orm/pg-core").PgColumn<{
            name: "acrisson";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        velocidadeLinha: import("drizzle-orm/pg-core").PgColumn<{
            name: "velocidade_linha";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        coreAttach: import("drizzle-orm/pg-core").PgColumn<{
            name: "core_attach";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        coreWrap: import("drizzle-orm/pg-core").PgColumn<{
            name: "core_wrap";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        surge: import("drizzle-orm/pg-core").PgColumn<{
            name: "surge";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        cuffEnd: import("drizzle-orm/pg-core").PgColumn<{
            name: "cuff_end";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bead: import("drizzle-orm/pg-core").PgColumn<{
            name: "bead";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        legElastic: import("drizzle-orm/pg-core").PgColumn<{
            name: "leg_elastic";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        cuffElastic: import("drizzle-orm/pg-core").PgColumn<{
            name: "cuff_elastic";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        temporary: import("drizzle-orm/pg-core").PgColumn<{
            name: "temporary";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        topsheet: import("drizzle-orm/pg-core").PgColumn<{
            name: "topsheet";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        backsheet: import("drizzle-orm/pg-core").PgColumn<{
            name: "backsheet";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        frontal: import("drizzle-orm/pg-core").PgColumn<{
            name: "frontal";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        earAttach: import("drizzle-orm/pg-core").PgColumn<{
            name: "ear_attach";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        pulpFix: import("drizzle-orm/pg-core").PgColumn<{
            name: "pulp_fix";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        central: import("drizzle-orm/pg-core").PgColumn<{
            name: "central";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        release: import("drizzle-orm/pg-core").PgColumn<{
            name: "release";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        tapeOnBag: import("drizzle-orm/pg-core").PgColumn<{
            name: "tape_on_bag";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        filme1x1: import("drizzle-orm/pg-core").PgColumn<{
            name: "filme_1x1";
            tableName: "coleta_grupo1";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const coletaGrupo2: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "coleta_grupo2";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: "always";
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "coleta_grupo2";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        dataColeta: import("drizzle-orm/pg-core").PgColumn<{
            name: "data_coleta";
            tableName: "coleta_grupo2";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        linhaProducao: import("drizzle-orm/pg-core").PgColumn<{
            name: "linha_producao";
            tableName: "coleta_grupo2";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        sku: import("drizzle-orm/pg-core").PgColumn<{
            name: "sku";
            tableName: "coleta_grupo2";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        pesoSacolaVarpe: import("drizzle-orm/pg-core").PgColumn<{
            name: "peso_sacola_varpe";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        parametroPainel: import("drizzle-orm/pg-core").PgColumn<{
            name: "parametro_painel";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        acrisson: import("drizzle-orm/pg-core").PgColumn<{
            name: "acrisson";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        velocidadeLinha: import("drizzle-orm/pg-core").PgColumn<{
            name: "velocidade_linha";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        waistPacker: import("drizzle-orm/pg-core").PgColumn<{
            name: "waist_packer";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isgElastic: import("drizzle-orm/pg-core").PgColumn<{
            name: "isg_elastic";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        waistElastic: import("drizzle-orm/pg-core").PgColumn<{
            name: "waist_elastic";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isgSideSeal: import("drizzle-orm/pg-core").PgColumn<{
            name: "isg_side_seal";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        absorventFix: import("drizzle-orm/pg-core").PgColumn<{
            name: "absorvent_fix";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        outerEdge: import("drizzle-orm/pg-core").PgColumn<{
            name: "outer_edge";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        inner: import("drizzle-orm/pg-core").PgColumn<{
            name: "inner";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        bead: import("drizzle-orm/pg-core").PgColumn<{
            name: "bead";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        standingGather: import("drizzle-orm/pg-core").PgColumn<{
            name: "standing_gather";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        backflimFix: import("drizzle-orm/pg-core").PgColumn<{
            name: "backflim_fix";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        osgSideSeal: import("drizzle-orm/pg-core").PgColumn<{
            name: "osg_side_seal";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        osgElastico: import("drizzle-orm/pg-core").PgColumn<{
            name: "osg_elastico";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        nwSealContLateral: import("drizzle-orm/pg-core").PgColumn<{
            name: "nw_seal_cont_lateral";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        nwSealIntCentRal: import("drizzle-orm/pg-core").PgColumn<{
            name: "nw_seal_int_cent_ral";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        outSideBackFlm: import("drizzle-orm/pg-core").PgColumn<{
            name: "out_side_back_flm";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        topsheetFix: import("drizzle-orm/pg-core").PgColumn<{
            name: "topsheet_fix";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        coreWrap: import("drizzle-orm/pg-core").PgColumn<{
            name: "core_wrap";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        coreWrapSeal: import("drizzle-orm/pg-core").PgColumn<{
            name: "core_wrap_seal";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        matFix: import("drizzle-orm/pg-core").PgColumn<{
            name: "mat_fix";
            tableName: "coleta_grupo2";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const insertColetaGrupo1Schema: z.ZodObject<Pick<{
    createdAt: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
    dataColeta: z.ZodString;
    linhaProducao: z.ZodString;
    sku: z.ZodOptional<z.ZodString>;
    pesoSacolaVarpe: z.ZodOptional<z.ZodNumber>;
    parametroPainel: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    acrisson: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    velocidadeLinha: z.ZodNumber;
    coreAttach: z.ZodNumber;
    coreWrap: z.ZodNumber;
    surge: z.ZodNumber;
    cuffEnd: z.ZodNumber;
    bead: z.ZodNumber;
    legElastic: z.ZodNumber;
    cuffElastic: z.ZodNumber;
    temporary: z.ZodNumber;
    topsheet: z.ZodNumber;
    backsheet: z.ZodNumber;
    frontal: z.ZodNumber;
    earAttach: z.ZodNumber;
    pulpFix: z.ZodNumber;
    central: z.ZodNumber;
    release: z.ZodNumber;
    tapeOnBag: z.ZodNumber;
    filme1x1: z.ZodNumber;
}, "dataColeta" | "linhaProducao" | "sku" | "pesoSacolaVarpe" | "parametroPainel" | "acrisson" | "velocidadeLinha" | "coreAttach" | "coreWrap" | "surge" | "cuffEnd" | "bead" | "legElastic" | "cuffElastic" | "temporary" | "topsheet" | "backsheet" | "frontal" | "earAttach" | "pulpFix" | "central" | "release" | "tapeOnBag" | "filme1x1">, "strip", z.ZodTypeAny, {
    dataColeta: string;
    linhaProducao: string;
    velocidadeLinha: number;
    coreAttach: number;
    coreWrap: number;
    surge: number;
    cuffEnd: number;
    bead: number;
    legElastic: number;
    cuffElastic: number;
    temporary: number;
    topsheet: number;
    backsheet: number;
    frontal: number;
    earAttach: number;
    pulpFix: number;
    central: number;
    release: number;
    tapeOnBag: number;
    filme1x1: number;
    sku?: string | undefined;
    pesoSacolaVarpe?: number | undefined;
    parametroPainel?: number | null | undefined;
    acrisson?: number | null | undefined;
}, {
    dataColeta: string;
    linhaProducao: string;
    velocidadeLinha: number;
    coreAttach: number;
    coreWrap: number;
    surge: number;
    cuffEnd: number;
    bead: number;
    legElastic: number;
    cuffElastic: number;
    temporary: number;
    topsheet: number;
    backsheet: number;
    frontal: number;
    earAttach: number;
    pulpFix: number;
    central: number;
    release: number;
    tapeOnBag: number;
    filme1x1: number;
    sku?: string | undefined;
    pesoSacolaVarpe?: number | undefined;
    parametroPainel?: number | null | undefined;
    acrisson?: number | null | undefined;
}>;
export declare const insertColetaGrupo2Schema: z.ZodObject<Pick<{
    createdAt: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
    dataColeta: z.ZodString;
    linhaProducao: z.ZodString;
    sku: z.ZodOptional<z.ZodString>;
    pesoSacolaVarpe: z.ZodOptional<z.ZodNumber>;
    parametroPainel: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    acrisson: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    velocidadeLinha: z.ZodNumber;
    waistPacker: z.ZodNumber;
    isgElastic: z.ZodNumber;
    waistElastic: z.ZodNumber;
    isgSideSeal: z.ZodNumber;
    absorventFix: z.ZodNumber;
    outerEdge: z.ZodNumber;
    inner: z.ZodNumber;
    bead: z.ZodNumber;
    standingGather: z.ZodNumber;
    backflimFix: z.ZodNumber;
    osgSideSeal: z.ZodNumber;
    osgElastico: z.ZodNumber;
    nwSealContLateral: z.ZodNumber;
    nwSealIntCentRal: z.ZodNumber;
    outSideBackFlm: z.ZodNumber;
    topsheetFix: z.ZodNumber;
    coreWrap: z.ZodNumber;
    coreWrapSeal: z.ZodNumber;
    matFix: z.ZodNumber;
}, "dataColeta" | "linhaProducao" | "sku" | "pesoSacolaVarpe" | "parametroPainel" | "acrisson" | "velocidadeLinha" | "coreWrap" | "bead" | "waistPacker" | "isgElastic" | "waistElastic" | "isgSideSeal" | "absorventFix" | "outerEdge" | "inner" | "standingGather" | "backflimFix" | "osgSideSeal" | "osgElastico" | "nwSealContLateral" | "nwSealIntCentRal" | "outSideBackFlm" | "topsheetFix" | "coreWrapSeal" | "matFix">, "strip", z.ZodTypeAny, {
    dataColeta: string;
    linhaProducao: string;
    velocidadeLinha: number;
    coreWrap: number;
    bead: number;
    waistPacker: number;
    isgElastic: number;
    waistElastic: number;
    isgSideSeal: number;
    absorventFix: number;
    outerEdge: number;
    inner: number;
    standingGather: number;
    backflimFix: number;
    osgSideSeal: number;
    osgElastico: number;
    nwSealContLateral: number;
    nwSealIntCentRal: number;
    outSideBackFlm: number;
    topsheetFix: number;
    coreWrapSeal: number;
    matFix: number;
    sku?: string | undefined;
    pesoSacolaVarpe?: number | undefined;
    parametroPainel?: number | null | undefined;
    acrisson?: number | null | undefined;
}, {
    dataColeta: string;
    linhaProducao: string;
    velocidadeLinha: number;
    coreWrap: number;
    bead: number;
    waistPacker: number;
    isgElastic: number;
    waistElastic: number;
    isgSideSeal: number;
    absorventFix: number;
    outerEdge: number;
    inner: number;
    standingGather: number;
    backflimFix: number;
    osgSideSeal: number;
    osgElastico: number;
    nwSealContLateral: number;
    nwSealIntCentRal: number;
    outSideBackFlm: number;
    topsheetFix: number;
    coreWrapSeal: number;
    matFix: number;
    sku?: string | undefined;
    pesoSacolaVarpe?: number | undefined;
    parametroPainel?: number | null | undefined;
    acrisson?: number | null | undefined;
}>;
export declare const insertAuthConfigSchema: z.ZodObject<Pick<{
    id: z.ZodOptional<z.ZodNumber>;
    accessCode: z.ZodString;
}, "accessCode">, "strip", z.ZodTypeAny, {
    accessCode: string;
}, {
    accessCode: string;
}>;
export type InsertAuthConfig = z.infer<typeof insertAuthConfigSchema>;
export type AuthConfig = typeof authConfig.$inferSelect;
export type InsertColetaGrupo1 = z.infer<typeof insertColetaGrupo1Schema>;
export type InsertColetaGrupo2 = z.infer<typeof insertColetaGrupo2Schema>;
export type ColetaGrupo1 = typeof coletaGrupo1.$inferSelect;
export type ColetaGrupo2 = typeof coletaGrupo2.$inferSelect;
